version: '3'

services:
  retrieval-query-api:
    build:
      context: .
      dockerfile: ./Dockerfile.retrieval
    environment:
      OPENAI_API_KEY: "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"
    volumes:
      - ./ragtest:/workspaces/wulo-graph-index/ragtest:rw
    ports:
      - "8000:8000"
    networks:
      - api-network

  legal-research-api:
    build:
      context: .
      dockerfile: ./Dockerfile.legal
    environment:
      OPENAI_API_KEY: "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"
    volumes:
      - ./ResearchCrew:/app/ResearchCrew:ro
    ports:
      - "8001:8001"
    depends_on:
      - retrieval-query-api
    networks:
      - api-network

networks:
  api-network:
    driver: bridge